### ISSUE TITLE
0.4.0 - Upgrading causes tests to fail

### ISSUE THREAD

**Issue by taijuten** [mjancarik/shallow-with-context#6]
I'm afraid I haven't had the opportunity to look into the recent changes, to see what may be causing this, but thought I'd raise the issue to make you aware.

Upgrading to 0.4.0 (with no other changes) causes

```
TypeError: (0 , _shallowWithContext.withContext) is not a function
```

**Comment by mjancarik** [comment]
Hi,

Thanks for report. I added other file with js extension. Please could you try 0.4.1 version?

**Comment by taijuten** [comment]
I'm afraid that now causes:
```
TypeError: Cannot read property 'aroundMethod' of undefined
```

**Comment by mjancarik** [comment]
We are going to right way. Could you send me more information about your configs (node version, babel config, test runner config).

**Comment by taijuten** [comment]
Certainly (and thank you for your help so far)
Node 12.x
Create React App with no other babel configuration
Jest/enzyme test runner (as per CRA) with no custom configuration.

Only possible difference in out-of-the-box test running is that we use `jest-sonar-reporter` as the results processor, but this is used for coverage checking, so shouldn't affect the test run

**Comment by mjancarik** [comment]
Hi,

I fixed other packages. I created new CRA app and everything works for me now. Could you confirm too? Only reinstall your dependencies.

**Comment by taijuten** [comment]
I've tried once more, but still see the same issues.
I notice that the package version is still 0.4.1 and there appear to be no further commits on github. Have you re-published the package?

**Comment by taijuten** [comment]
Hi @mjancarik,

This appears to be working for me now. Thanks very much for looking into this and spending your precious time on it :+1:
